FOOD_IMAGE_MAP = {
    ""
    "Aloo gobi": "https://static01.nyt.com/images/2023/12/21/multimedia/ND-Aloo-Gobi-gkwc/ND-Aloo-Gobi-gkwc-threeByTwoLargeAt2X.jpg",
    "Aloo matar": "https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Punjabi-Aloo-Matar-Recipe.jpg",
    "Aloo methi": "https://www.cookwithmanali.com/wp-content/uploads/2019/04/Aloo-Methi-500x375.jpg",
    "Aloo shimla mirch": "https://www.enhanceyourpalate.com/wp-content/uploads/Aloo-Shimla-Mirch-–-Bell-Pepper-Potatoes-Stir-Fry.jpg",
    "Aloo tikki": "https://www.indianveggiedelight.com/wp-content/uploads/2023/07/aloo-tikki-featured.jpg",
    "Alu Pitika": "https://www.pepperonpizza.com/wp-content/uploads/2017/12/Aloo-Pitika_F.jpg",
    "Amti": "https://i.ytimg.com/vi/SOxp38zoCNg/sddefault.jpg",
    "Anarsa": "https://m.media-amazon.com/images/I/71cxGDKUubL.jpg",
    "Ariselu": "https://vellankifoods.com/cdn/shop/products/ariselu_ghee.jpg?v=1679896343",
    "Avial": "https://rakskitchen.net/wp-content/uploads/2010/04/avial-recipe.jpg",
    "Baingan Fry": "https://i.ytimg.com/vi/DkxNg08THzE/maxresdefault.jpg",
    "Bajri no rotlo": "https://www.cookclickndevour.com/wp-content/uploads/2017/04/bajra-roti-recipe-g-683x1024.jpg",
    "Balu shahi": "https://www.cubesnjuliennes.com/wp-content/uploads/2019/03/Halwai-Style-Balushahi-Recipe.jpg",
    "Bandar laddu": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKdh6fMJ_ZFFtpNGWWfosUv5-cLDOy8JTBjA&s",
    "Basundi": "https://www.sharmispassions.com/wp-content/uploads/2014/12/basundi4.jpg",
    "Bebinca": "https://d1mxd7n691o8sz.cloudfront.net/static/recipe/recipe/2023-12/3ec25abc12f7497d813a82f27496d069-8f2d4b9719ba47868c9c92f1b8be5870_thumbna.jpeg",
    "Bengena Pitika": "https://static.india.com/wp-content/uploads/2024/07/bengana-pitika.jpg",
    "Bhakri": "https://zanzaneetkitchen.com/wp-content/uploads/2023/02/JowarBhakri.png",
    "Bhatura": "https://www.indianhealthyrecipes.com/wp-content/uploads/2019/09/bhatura-recipe.jpg",
    "Bhindi masala": "https://greenbowl2soul.com/wp-content/uploads/2019/05/bhindi-masala.jpg",
    "Bilahi Maas": "https://i.pinimg.com/564x/6b/f3/f1/6bf3f138a861d60a0292862ec6777828.jpg",
    "Biryani": "https://t4.ftcdn.net/jpg/18/47/47/21/360_F_1847472123_ea7Lzzy7vaIvNjeXAlEQOOHKK4qZQSkV.jpg",
    "Bisi bele bath": "https://maayeka.com/wp-content/uploads/2019/12/bisi-bele-bhath.jpg",
    "Black rice": "https://yupitsvegan.com/wp-content/uploads/2015/12/rice-cooker-black-rice.jpg",
    "Bombil fry": "https://www.licious.in/blog/wp-content/uploads/2022/08/shutterstock_1865951416.jpg",
    "Boondi": "https://theflavoursofkitchen.com/wp-content/uploads/2021/10/Sweet-boondi-2-scaled.jpg",
    "Bora Sawul": "https://images.livemint.com/img/2021/04/14/original/Assamese_Jolpaan_Bihu_Mint_Lounge_1618365587137.jpg",
    "Brown Rice": "https://thumbs.dreamstime.com/b/cooked-thai-organic-red-jasmine-rice-white-plate-semi-milled-including-fiber-b-vitamins-magnesium-offering-richer-331854133.jpg",
    "Butter chicken": "https://images.pexels.com/photos/7625056/pexels-photo-7625056.jpeg?cs=srgb&dl=pexels-saveurssecretes-7625056.jpg&fm=jpg",
    "Chak Hao Kheer": "https://thericechick.com/wp-content/uploads/2022/06/social-chak-hao-kheer.jpg",
    "Chakali": "https://images.pexels.com/photos/5992272/pexels-photo-5992272.jpeg?cs=srgb&dl=pexels-saveurssecretes-5992272.jpg&fm=jpg",
    "Cham cham": "https://t3.ftcdn.net/jpg/19/04/59/94/360_F_1904599408_xn1PsINtC3E2Gtc9q2fwTDV4hwnOQ8ql.jpg",
    "Chana masala": "https://www.kuchpakrahahai.in/wp-content/uploads/2023/02/Vegan-chana-masala.jpg",
    "Chapati": "https://thumbs.dreamstime.com/b/indian-food-chapati-flat-bread-made-wheat-flour-dough-traditional-popular-cuisine-64427630.jpg", 
    "Cheera Doi": "https://images.slurrp.com/prod/articles/18fnbzecsc6h.webp?impolicy=slurrp-20210601&width=1200&height=900",
    "Chevdo": "https://www.shutterstock.com/image-photo/variety-savory-snacks-white-bowl-600nw-2563688811.jpg",
    "Chhena jalebi": "https://www.shutterstock.com/image-photo/paneer-jalebi-know-chhena-jilapi-260nw-1258952050.jpg",
    "Chhena kheeri": "https://upload.wikimedia.org/wikipedia/commons/e/ea/Chhena_kheeri.png",
    "Chhena poda": "https://www.bigbasket.com/media/uploads/recipe/w-l/4570_2_1.jpg",
    "Chicken razala": "https://www.whiskaffair.com/wp-content/uploads/2018/12/Bengali-Chicken-Rezala-2-3.jpg",
    "Chicken Tikka": "https://t4.ftcdn.net/jpg/05/85/17/03/360_F_585170352_7D9PjNXOvU3PAB4ynMRWpEavhBNuLG3J.jpg",
    "Chicken Tikka masala": "https://www.shutterstock.com/image-photo/chicken-tikka-masala-spices-on-600nw-2700643187.jpg",
    "Chicken Varuval": "https://www.cubesnjuliennes.com/wp-content/uploads/2018/12/Spicy-Chicken-Fry-Recipe-500x500.jpg",
    "Chikki": "https://t3.ftcdn.net/jpg/04/71/74/90/360_F_471749003_QqBGZUJm4BIpkDrbfCI02NJtznUhdDrG.jpg",
    "Chingri Bhape": "https://peekncooksa.blob.core.windows.net/index-recipe/bengali_steamed_prawn.jpg",
    "Chingri malai curry": "https://i.ytimg.com/vi/SWfWrva091Y/maxresdefault.jpg",
    "Chole bhature": "https://madhurasrecipe.com/wp-content/uploads/2025/09/MR-Chole-Bhature-featured.jpg",
    "Chorafali": "https://www.nehascookbook.com/wp-content/uploads/2022/10/Cholafali-WS.jpg",
    "Churma Ladoo": "",
    "Coconut vadi": "",
    "Copra paak": "",
    "Currivepillai sadam": "",
    "Daal baati churma": "",
    "Daal Dhokli": "",
    "Daal puri": "",
    "Dahi vada": "",
    "Dal makhani": "",
    "Dal tadka": "",
    "Dalithoy": "",
    "Dharwad pedha": "",
    "Dhokla": "",
    "Dhondas": "",
    "Doodhpak": "",
    "Dosa": "",
    "Double ka meetha": "",
    "Dum aloo": "",
    "Dudhi halwa": "",
}