FOOD_IMAGE_MAP = {
    ""
    "Aloo gobi": "https://www.vegrecipesofindia.com/wp-content/uploads/2013/11/gobi-masala-recipe-500x500.jpg",
    "Aloo matar": "https://www.vegrecipesofindia.com/wp-content/uploads/2013/11/gobi-masala-recipe-500x500.jpg",
    "Aloo methi": "https://www.vegrecipesofindia.com/wp-content/uploads/2013/11/gobi-masala-recipe-500x500.jpg",
    "Aloo shimla mirch": "https://www.vegrecipesofindia.com/wp-content/uploads/2014/06/bharwan-shimla-mirch-recipe-500x500.jpg",
    "Aloo tikki": "https://www.vegrecipesofindia.com/wp-content/uploads/2012/12/aloo-tikki-chole-500x500.jpg",
    "Alu Pitika": "https://www.pepperonpizza.com/wp-content/uploads/2019/04/Assamese-Aloo-Pitika-1024x768.jpg?ezimgfmt=ng:webp/ngcb10",
    "Amti": "https://www.vegrecipesofindia.com/wp-content/uploads/2014/02/amti-recipe.jpg",
    "Anarsa": "https://www.crazymasalafood.com/wp-content/images/anarsa.jpg",
    "Ariselu": "https://www.crazymasalafood.com/wp-content/images/anarsa.jpg",
    "Attu": "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl_sunitha/Andhra_Style_Andhra_Kandi_Attu_Recipe_Toor_Dal_Dosa_Recipe_.jpg",
    "Avial": "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl_sunitha/Andhra_Style_Andhra_Kandi_Attu_Recipe_Toor_Dal_Dosa_Recipe_.jpg",
    "Baingan Fry": "https://i.ytimg.com/vi/DkxNg08THzE/maxresdefault.jpg",
    "Bajri no rotlo": "",
    "Balu shahi": "",
    "Bandar laddu": "",
    "Basundi": "",
    "Bebinca": "",
    "Bengena Pitika": "",
    "Bhakri": "",
    "Bhatura": "",
    "Bhindi masala": "",
    "Bilahi Maas": "",
    "Biryani": "",
    "Bisi bele bath": "",
    "Black rice": "",
    "Bombil fry": "",
    "Boondi": "",
    "Bora Sawul": "",
    "Brown Rice": "",
    "Butter chicken": "",
}